### ISSUE TITLE
Private bin changed protocols 

### ISSUE THREAD

**Issue by rbluer** [InstantlyMoist/privatebin-java-api#2]
It looks like private bin v1.7.x has changed their protocols and as such it is a breaking change for privatebin-java-api.

Off hand I'm not too sure about the encryption protocols and what exactly changed, or what needs to be changed to resolve the current issue.

When using privatebin-java-api I'm getting the following stacktrace below...

How I'm using your library:
```	
        Paste paste = new Paste("https://privatebin.net")
                .setMessage( text )
                .setExpire( getExpire( expire ) )
                .setPasteFormat( PasteFormat.PLAINTEXT )
                .setUserPassword( password )
                .encrypt();

        String pasteUrl = paste.send();
```

```
[16:37:15 WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
[16:37:15 WARN]:        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
[16:37:15 WARN]:        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
[16:37:15 WARN]:        at sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
[16:37:15 WARN]:        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
[16:37:15 WARN]:        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
[16:37:15 WARN]:        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:155)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1315)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1228)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:384)
[16:37:15 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
[16:37:15 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[16:37:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1354)
[16:37:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1329)
[16:37:15 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
[16:37:15 WARN]:        at nl.kyllian.models.Paste.send(Paste.java:199)
[16:37:15 WARN]:        at tech.mcprison.prison.discord.PrisonPasteChat.postPrivateBin(PrisonPasteChat.java:254)
[16:37:15 WARN]:        at tech.mcprison.prison.discord.PrisonPasteChat.post(PrisonPasteChat.java:119)
[16:37:15 WARN]:        at tech.mcprison.prison.discord.PrisonPasteChat.post(PrisonPasteChat.java:88)
[16:37:15 WARN]:        at tech.mcprison.prison.PrisonCommand.supportSubmitVersion(PrisonCommand.java:1541)
[16:37:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:37:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:37:15 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:37:15 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.executeMethod(RegisteredCommand.java:256)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:211)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:205)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:205)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:205)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.CommandHandler.onCommand(CommandHandler.java:986)
[16:37:15 WARN]:        at tech.mcprison.prison.spigot.SpigotPlatform$1.execute(SpigotPlatform.java:478)
[16:37:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:37:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:37:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:37:15 WARN]:        at java.lang.Thread.run(Thread.java:750)
[16:37:15 WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version
[16:37:15 WARN]:        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
[16:37:15 WARN]:        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
[16:37:15 WARN]:        at sun.security.ssl.TransportContext.fatal(TransportContext.java:356)
[16:37:15 WARN]:        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
[16:37:15 WARN]:        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:202)
[16:37:15 WARN]:        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:155)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1315)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1228)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
[16:37:15 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:384)
[16:37:15 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
[16:37:15 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
[16:37:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1584)
[16:37:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
[16:37:15 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[16:37:15 WARN]:        at nl.kyllian.models.Paste.send(Paste.java:207)
[16:37:15 WARN]:        at tech.mcprison.prison.discord.PrisonPasteChat.postPrivateBin(PrisonPasteChat.java:254)
[16:37:15 WARN]:        at tech.mcprison.prison.discord.PrisonPasteChat.post(PrisonPasteChat.java:119)
[16:37:15 WARN]:        at tech.mcprison.prison.discord.PrisonPasteChat.post(PrisonPasteChat.java:88)
[16:37:15 WARN]:        at tech.mcprison.prison.PrisonCommand.supportSubmitVersion(PrisonCommand.java:1541)
[16:37:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:37:15 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:37:15 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:37:15 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.executeMethod(RegisteredCommand.java:256)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:211)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:205)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:205)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.RegisteredCommand.execute(RegisteredCommand.java:205)
[16:37:15 WARN]:        at tech.mcprison.prison.commands.CommandHandler.onCommand(CommandHandler.java:986)
[16:37:15 WARN]:        at tech.mcprison.prison.spigot.SpigotPlatform$1.execute(SpigotPlatform.java:478)
[16:37:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:37:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[16:37:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[16:37:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[16:37:15 WARN]:        at java.lang.Thread.run(Thread.java:750)
```

If you have any suggestions, or need more info, please let me know.  
 Thanks,
   Blue

**Comment by rbluer** [comment]
Found the issue.

I'm not sure what exactly changed on privatebin's side, but it appears as if they are now requiring the use of **TLSv1.3** and as such, older versions of java 1.8 does is not supported since they only support up to **TLSv1.2**.

The solution to get this library to work properly with privatebin is to update Java to a more recent release that supports **TLSv1.3**.

Oracle's Java 1.8.0_411 supports **TLSv1.3**.  I'm not sure about open JDK, but the latest release should support it.

In my fork, I've added junit test that tries to paste a two line message to a privatebin server, and if it fails, it inspects the current java version and what TLS versions are available.  If it detects that 1.8 is being used and TLSv1.3 is not available, it then logs a message indicating that the java release needs to be updated.

Also I'm addressing the issue with the inability to suppress stack traces when such an error happens.  Paste.send() throws exceptions, but with this error, it's catching two exceptions and generating stack traces, then a third, non-related issue causes `send()` to throw another error.  Likewise, when a related error occurs, and if it's able to determine that it related to the lack of a the TLSv1.3 protocol, it will provide more detailed information on how to resolve the issues.

**Comment by InstantlyMoist** [comment]
Hey, 

Appreciated, feel free to open a PR :)

**Comment by rbluer** [comment]
Thanks.  I will create a PR, but first I want to make sure everything is working as expected.

I did notice that even with java jdk-1.8_411 that it is failing to use a good protocol when running on my test servers.  It works fine with the unit tests, so I need to double check things to ensure I'm not doing something odd with my servers.  It I'm having issues, then our customers will have issues too, since they may have less flexibility on the servers they are leasing.

So I may need to dig a little deeper and see what else may be going on with it.

**Comment by rbluer** [comment]
I realized that in my testing of this plugin, I inadvertently had the server setting '-Dhttps.protocols=TLSv1.2`, of which forced the protocol to fail, because it forces the use of `TLSv1.2` even though `TLSv1.3` is available.  So this works fine with Java jdk-1.8_411.

So the perceived failure was in error, and is not an issue.
